name: Publish Quantities Units

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Quantities.Units.csproj'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  Prefix: 'quantities.units'
  Project: 'Quantities.Units/Quantities.Units.csproj'
  DotNetVersion: 7.0.x

defaults:
  run:
    working-directory: source

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DotNetVersion }}
      - uses: tedd/publish-nuget-neo@v1
        with:
          NUGET_KEY: ${{secrets.PUSH_NEW_QUANTITY_VERSION}}
          PROJECT_FILE_PATH: ${{env.Project}}
          TAG_COMMIT: true
          TAG_FORMAT: ${{env.Prefix}}/v*
