name: Publish Quantities System Text Json Serialization

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Atmoos.Quantities.Serialization.Text.Json.csproj'

jobs:
  publish-quantities-serialization-text-json:
    uses: ./.github/workflows/publish-library.yml
    with:
      project-path: 'source/Atmoos.Quantities.Serialization/Text.Json/Atmoos.Quantities.Serialization.Text.Json.csproj'
      tag-prefix: 'quantities/serialization/text.json'
    secrets: inherit
