name: Publish Core Quantities

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Atmoos.Quantities.csproj'

jobs:
  publish-quantities:
    uses: ./.github/workflows/publish-library.yml
    with:
      project-path: 'source/Atmoos.Quantities/Atmoos.Quantities.csproj'
      tag-prefix: 'quantities'
    secrets: inherit
