name: Publish Quantities Newtonsoft Serialization

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Atmoos.Quantities.Serialization.Newtonsoft.csproj'

jobs:
  publish-quantities-serialization-newtonsoft:
    uses: ./.github/workflows/publish-library.yml
    with:
      project-path: 'source/Atmoos.Quantities.Serialization/Newtonsoft/Atmoos.Quantities.Serialization.Newtonsoft.csproj'
      tag-prefix: 'quantities/serialization/newtonsoft'
    secrets: inherit