name: Publish Quantities Units

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Atmoos.Quantities.Units.csproj'

jobs:
  publish-quantities-units:
    uses: ./.github/workflows/publish-library.yml
    with:
      project-path: 'source/Atmoos.Quantities.Units/Atmoos.Quantities.Units.csproj'
      tag-prefix: 'quantities.units'
    secrets: inherit
